# Site settings
title: Model EU Strasbourg
email: contact@meu-strasbourg.org
description: >
  Model European Union Strasbourg (MEUS) is a unique simulation of EU
  decision-making and politics, taking place annually in Strasbourg.
keywords: >
  Model European Union, Political Simulation, MEU, MEUS, EU Politics,
  European Politics, European Parliament, Strasbourg, Original MEU
# the subpath of your site, e.g. /blog/
baseurl: "http://www.meu-strasbourg.org"
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: modeleu
github_username:  beta-europe
facebook_page: meustrasbourg

next_conference: "in April 2016"

# Build settings
markdown: kramdown


gems: [jekyll-paginate]
paginate: 4
paginate_path: "announcements/page:num"